### ISSUE TITLE
How to load it lazy with NeoBundle?

### ISSUE THREAD

**Issue by amerlyq** [jamessan/vim-gnupg#53]
I have next recipe for NeoBundle
```
jamessan/vim-gnupg:
  description: Edit and save encrypted '*.gpg' files in-place
  external_commands: gpg
  augroup: GnuPG
  filename_patterns: ['\.gpg$', '\.asc$', '\.pgp$']
  lazy: 1
```
And corresponding part in vimrc
```
if neobundle#tap('vim-gnupg') "{{{
  fun! neobundle#hooks.on_post_source(bundle)
    silent! exe 'doautocmd GnuPG BufReadCmd'
  endf
  call neobundle#untap()
endif "}}}
```
So, I assumed that calling BufReadCmd will do the work. It seems not so, because on manual calling autocmd, instead of usual behaviour, only first several lines of encrypted text are rewritten (with exact decrypted text). And by using 'u' I can undo this text back to encrypted container -- which wierd.
Which steps I must manually do in on_post_source or on_source hooks to complete expected initialization of this plugin?
